import { useEffect, useMemo, useState } from "react";
import { FileText, Loader2, PackageX, Search, Download, ShieldAlert, Pencil, Trash2, X, ImagePlus } from "lucide-react";
import api from "@/lib/api";
import ImageUpload, { ImageHover } from "@/components/ImageUpload";
import { toast } from "sonner";

const today = () => new Date().toISOString().slice(0, 10);
const inputClass = "w-full h-11 bg-slate-950 border border-slate-700 rounded-lg px-3 text-slate-100 outline-none focus:ring-2 focus:ring-red-500";
const labelClass = "block text-xs font-semibold text-slate-400 mb-2 uppercase tracking-wider";
const emptyForm = { holder_id: "", quantity: "", scrap_reason: "", description: "", scrap_date: today(), location: "", operator_personnel_id: "", approver_personnel_id: "", witness_personnel_id: "", before_image_url: "", after_image_url: "", before_image_urls: [], after_image_urls: [] };
const reasons = ["Kırıldı", "Ezildi / deforme oldu", "Aşındı", "Ölçü toleransı dışına çıktı", "Yanlış kullanım kaynaklı hasar", "Korozyon / paslanma", "Kayboldu / bulunamıyor", "Diğer"];
const personName = (p) => `${p.first_name || ""} ${p.last_name || ""}`.trim();

function MultiPhotoUpload({ value = [], onChange, label }) {
  const [uploading, setUploading] = useState(false);
  const files = Array.isArray(value) ? value : (value ? [value] : []);
  const onFiles = async (event) => {
    const selectedFiles = Array.from(event.target.files || []).filter((file) => file.type.startsWith("image/"));
    if (!selectedFiles.length) return toast.error("Lütfen görsel dosyası seçin");
    const tooLarge = selectedFiles.find((file) => file.size > 5 * 1024 * 1024);
    if (tooLarge) return toast.error("Her görsel en fazla 5 MB olabilir");
    setUploading(true);
    try {
      const uploaded = [];
      for (const file of selectedFiles) {
        const data = new FormData(); data.append("file", file);
        const response = await api.post("/images/upload", data, { headers: { "Content-Type": "multipart/form-data" } });
        uploaded.push(response.data.image_url);
      }
      onChange([...files, ...uploaded]);
      toast.success(`${uploaded.length} görsel yüklendi`);
    } catch (error) { toast.error(error.response?.data?.detail || "Görseller yüklenemedi"); }
    finally { setUploading(false); event.target.value = ""; }
  };
  return <div><label className="block text-sm font-black text-slate-800 mb-2">{label}</label><div className="flex flex-wrap items-center gap-3"><label className="inline-flex items-center gap-2 px-4 h-11 rounded-lg bg-slate-900 hover:bg-slate-700 text-white font-black cursor-pointer">{uploading ? <Loader2 className="w-4 h-4 animate-spin" /> : <ImagePlus className="w-4 h-4" />}{uploading ? "Yükleniyor..." : "Fotoğraf ekle"}<input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={onFiles} className="hidden" /></label>{files.map((src, index) => <div key={`${src}-${index}`} className="relative group w-20 h-20 rounded-lg overflow-hidden border-2 border-slate-300 bg-slate-100"><img src={src} alt={`${label} ${index + 1}`} className="w-full h-full object-cover" /><button type="button" onClick={() => onChange(files.filter((_, i) => i !== index))} className="absolute top-0 right-0 hidden group-hover:flex bg-red-700 text-white rounded-bl p-1" aria-label="Görseli kaldır"><X className="w-3 h-3" /></button><span className="absolute bottom-0 left-0 bg-slate-900/80 text-white text-[10px] px-1">{index + 1}</span></div>)}</div><p className="text-xs text-slate-500 mt-2">Birden fazla fotoğraf seçebilirsiniz. Fotoğraf başına en fazla 5 MB.</p></div>;
}

export default function HurdaTutucular() {
  const [holders, setHolders] = useState([]); const [scraps, setScraps] = useState([]); const [personnel, setPersonnel] = useState([]);
  const [form, setForm] = useState(emptyForm); const [search, setSearch] = useState(""); const [editingId, setEditingId] = useState(null); const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { const [h, s, p] = await Promise.all([api.get("/toolholders"), api.get("/toolholder-scraps"), api.get("/personnel")]); setHolders(h.data || []); setScraps(s.data || []); setPersonnel(p.data || []); } catch (e) { toast.error(e.response?.data?.detail || "Hurda kayıtları yüklenemedi"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => { const q = search.trim().toLowerCase(); return holders.filter((h) => !q || `${h.name} ${h.brand || ""} ${h.type || ""} ${h.cutting_tool_code_name || ""}`.toLowerCase().includes(q)); }, [holders, search]);
  const selected = holders.find((h) => h.id === form.holder_id); const set = (key, value) => setForm((f) => ({ ...f, [key]: value }));
  const reset = () => { setForm(emptyForm); setEditingId(null); };
  const edit = (s) => { setEditingId(s.id); setForm({ holder_id: s.tool_holder_id || "", quantity: String(s.quantity || ""), scrap_reason: s.scrap_reason || "", description: s.description || "", scrap_date: s.scrap_date || today(), location: s.location || "", operator_personnel_id: s.operator_personnel_id || "", approver_personnel_id: s.approver_personnel_id || "", witness_personnel_id: s.witness_personnel_id || "", before_image_url: s.before_image_url || "", after_image_url: s.after_image_url || "", before_image_urls: s.before_image_urls || (s.before_image_url ? [s.before_image_url] : []), after_image_urls: s.after_image_urls || (s.after_image_url ? [s.after_image_url] : []) }); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const submit = async (e) => { e.preventDefault(); if (!form.holder_id || !form.scrap_reason || !Number(form.quantity) || Number(form.quantity) <= 0) return toast.error("Tutucu, miktar ve hurda nedeni zorunludur"); const current = Number(selected?.current_stock || 0); const oldQty = editingId ? Number(scraps.find((s) => s.id === editingId)?.quantity || 0) : 0; if (!editingId && Number(form.quantity) > current) return toast.error("Hurda miktarı mevcut stoktan fazla olamaz"); if (editingId && current + oldQty < Number(form.quantity)) return toast.error("Bu düzeltme stok miktarını eksiye düşürüyor"); if (!window.confirm(editingId ? "Hurda kaydı düzeltilecek ve stok farkı uygulanacak. Devam edilsin mi?" : `${selected.name} tutucusundan ${form.quantity} adet hurdaya ayrılacak. Devam edilsin mi?`)) return; setSaving(true); try { const body = { quantity: Number(form.quantity), scrap_reason: form.scrap_reason, description: form.description, scrap_date: form.scrap_date, location: form.location, operator_personnel_id: form.operator_personnel_id, approver_personnel_id: form.approver_personnel_id, witness_personnel_id: form.witness_personnel_id, before_image_url: form.before_image_urls[0] || "", after_image_url: form.after_image_urls[0] || "", before_image_urls: form.before_image_urls, after_image_urls: form.after_image_urls }; const r = editingId ? await api.put(`/toolholder-scraps/${editingId}`, body) : await api.post(`/toolholders/${form.holder_id}/scrap`, body); toast.success(editingId ? `Hurda kaydı düzeltildi. Yeni stok: ${r.data.new_stock}` : `Hurda kaydı oluşturuldu. Yeni stok: ${r.data.new_stock}`); reset(); await load(); } catch (e) { toast.error(e.response?.data?.detail || "Hurda işlemi yapılamadı"); } finally { setSaving(false); } };
  const remove = async (s) => { if (!window.confirm(`${s.name} hurda kaydı silinsin mi? ${s.quantity} adet stok geri eklenecek.`)) return; try { const r = await api.delete(`/toolholder-scraps/${s.id}`); toast.success(`Kayıt silindi. Yeni stok: ${r.data.new_stock}`); if (editingId === s.id) reset(); await load(); } catch (e) { toast.error(e.response?.data?.detail || "Hurda kaydı silinemedi"); } };
  const downloadPdf = async (s) => { try { const r = await api.get(`/toolholder-scraps/${s.id}/pdf`, { responseType: "blob" }); const url = URL.createObjectURL(r.data); const a = document.createElement("a"); a.href = url; a.download = `hurda-tutanagi-${s.id.slice(0, 8)}.pdf`; a.click(); URL.revokeObjectURL(url); } catch (e) { toast.error(e.response?.data?.detail || "PDF tutanak indirilemedi"); } };
  const personSelect = (label, key) => <div><label className={labelClass}>{label}</label><select value={form[key]} onChange={(e) => set(key, e.target.value)} className={inputClass}><option value="">-- Personel seçin --</option>{personnel.map((p) => <option key={p.id} value={p.id}>{personName(p)}{p.department ? ` — ${p.department}` : ""}</option>)}</select></div>;
  return <div className="space-y-7">
    <div className="flex items-end justify-between gap-4 flex-wrap"><div><div className="text-xs text-red-500 uppercase tracking-[0.2em] font-bold mb-2">Stoktan Kullanım Dışı Ayırma</div><h1 className="font-display text-4xl font-black">Takım Tutucu Hurda / Kullanım Dışı</h1><p className="text-slate-700 mt-2 font-semibold">Kırılan, ezilen veya kullanılamaz duruma gelen tutucuları gerekçesiyle kaydedin ve stoktan düşürün.</p></div><div className="rounded-xl bg-red-50 border border-red-200 px-4 py-3 text-red-800 font-bold flex items-center gap-2"><ShieldAlert className="w-5 h-5" /> Hurda işlemi stoktan düşer</div></div>
    <div className="grid grid-cols-1 md:grid-cols-3 gap-4"><div className="bg-white border border-slate-200 rounded-2xl p-5"><div className="text-slate-600 font-bold text-sm">Tutucu çeşidi</div><div className="text-3xl font-black mt-2 text-slate-950">{holders.length}</div></div><div className="bg-white border border-slate-200 rounded-2xl p-5"><div className="text-slate-600 font-bold text-sm">Hurda kaydı</div><div className="text-3xl font-black mt-2 text-red-700">{scraps.length}</div></div><div className="bg-white border border-slate-200 rounded-2xl p-5"><div className="text-slate-600 font-bold text-sm">Toplam hurda miktarı</div><div className="text-3xl font-black mt-2 text-amber-700">{scraps.reduce((n, s) => n + Number(s.quantity || 0), 0)} adet</div></div></div>
    <form onSubmit={submit} className="bg-white border border-slate-200 rounded-2xl p-6 space-y-6 shadow-sm"><div className="flex items-center justify-between gap-3 text-red-700 font-black text-lg"><span className="flex items-center gap-3"><PackageX className="w-6 h-6" />{editingId ? "Hurda tutanağını düzelt" : "Hurda tutanağı oluştur"}</span>{editingId && <button type="button" onClick={reset} className="text-sm text-slate-700 flex items-center gap-1"><X className="w-4 h-4" /> İptal</button>}</div>
      <div><label className={labelClass}>Tutucu ara</label><div className="relative"><Search className="absolute left-3 top-3 w-4 h-4 text-slate-500" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Ad, marka, tip veya kesici uç kodu..." className={`${inputClass} pl-10`} /></div></div>
      <div><label className={labelClass}>Hurdaya ayrılacak takım tutucu</label><select required disabled={!!editingId} value={form.holder_id} onChange={(e) => set("holder_id", e.target.value)} className={inputClass}><option value="">-- Stoktan tutucu seçin --</option>{filtered.map((h) => <option key={h.id} value={h.id}>{h.name} | {h.brand || "-"} | Stok: {h.current_stock} adet</option>)}</select></div>
      {selected && <div className="rounded-xl bg-slate-50 border border-slate-200 p-4 grid grid-cols-2 md:grid-cols-5 gap-3 text-sm"><div><span className="text-slate-500 block font-bold">Tutucu</span><b>{selected.name}</b></div><div><span className="text-slate-500 block font-bold">Marka</span>{selected.brand || "-"}</div><div><span className="text-slate-500 block font-bold">Tip</span>{selected.type || "-"}</div><div><span className="text-slate-500 block font-bold">Ölçü</span>Boy {selected.length || "-"} / Çap {selected.diameter || "-"}</div><div><span className="text-slate-500 block font-bold">Mevcut stok</span><b className="text-emerald-700">{selected.current_stock} adet</b></div></div>}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4"><div><label className={labelClass}>Hurda miktarı</label><input required type="number" min="0.01" step="0.01" value={form.quantity} onChange={(e) => set("quantity", e.target.value)} className={inputClass} /></div><div><label className={labelClass}>Hurda nedeni</label><select required value={form.scrap_reason} onChange={(e) => set("scrap_reason", e.target.value)} className={inputClass}><option value="">-- Neden seçin --</option>{reasons.map((r) => <option key={r}>{r}</option>)}</select></div><div><label className={labelClass}>Hurda tarihi</label><input required type="date" value={form.scrap_date} onChange={(e) => set("scrap_date", e.target.value)} className={inputClass} /></div><div><label className={labelClass}>Konum / hurda alanı</label><input value={form.location} onChange={(e) => set("location", e.target.value)} placeholder="Hurda alanı" className={inputClass} /></div></div>
      <div><label className={labelClass}>Neden ve hasar açıklaması</label><textarea required value={form.description} onChange={(e) => set("description", e.target.value)} rows={3} placeholder="Hasarın nasıl oluştuğunu, ezilme/kırılma durumunu ve tespit notlarını yazın..." className="w-full bg-slate-950 border border-slate-700 rounded-lg p-3 text-slate-100 outline-none focus:ring-2 focus:ring-red-500" /></div>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">{personSelect("İşlemi yapan", "operator_personnel_id")}{personSelect("Onaylayan", "approver_personnel_id")}{personSelect("Tanık / teslim alan", "witness_personnel_id")}</div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4"><MultiPhotoUpload value={form.before_image_urls} onChange={(before_image_urls) => setForm({ ...form, before_image_urls, before_image_url: before_image_urls[0] || "" })} label="İlk Hali / Stoktaki Görseller" /><MultiPhotoUpload value={form.after_image_urls} onChange={(after_image_urls) => setForm({ ...form, after_image_urls, after_image_url: after_image_urls[0] || "" })} label="Son Hali / Bozuk-Ezik-Kırık Görseller" /></div>
      <button disabled={saving || loading} className="h-14 px-6 rounded-lg bg-red-700 hover:bg-red-600 disabled:opacity-50 text-white font-black flex items-center gap-2">{saving ? <Loader2 className="w-5 h-5 animate-spin" /> : <FileText className="w-5 h-5" />} {editingId ? "Düzeltmeyi Kaydet" : "Hurdaya Ayır ve Tutanağı Kaydet"}</button>
    </form>
    <div className="bg-white border border-slate-200 rounded-2xl overflow-hidden shadow-sm"><div className="p-5 border-b border-slate-200 flex items-center gap-2"><FileText className="w-5 h-5 text-red-700" /><h2 className="font-black text-lg text-slate-950">Hurda kayıtları ve tutanaklar</h2></div>{loading ? <div className="p-8 text-center"><Loader2 className="w-6 h-6 animate-spin inline" /></div> : scraps.length === 0 ? <div className="p-8 text-center text-slate-600 font-semibold">Henüz hurda kaydı yok.</div> : <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-slate-700 border-b border-slate-200"><th className="p-4">Tarih</th><th className="p-4">Tutucu</th><th className="p-4">Miktar</th><th className="p-4">Hurda nedeni</th><th className="p-4">Personel</th><th className="p-4">İşlem</th></tr></thead><tbody>{scraps.map((s) => <tr key={s.id} className="border-b border-slate-100 hover:bg-slate-50"><td className="p-4 font-bold text-slate-900">{s.scrap_date}</td><td className="p-4"><b>{s.name}</b><ImageHover src={(s.after_image_urls || [])[0] || s.after_image_url || (s.before_image_urls || [])[0] || s.before_image_url} alt={s.name} /><div className="text-slate-600">{s.brand || "-"} · {s.holder_type || "-"}</div></td><td className="p-4 font-black text-red-700">{s.quantity} adet</td><td className="p-4 font-bold text-slate-900">{s.scrap_reason}<div className="text-slate-600 font-normal max-w-xs">{s.description || "-"}</div></td><td className="p-4 text-slate-700"><div>İşlemi yapan: {s.operator_name || s.user_name || "-"}</div><div>Onay: {s.approved_by || "-"}</div><div>Tanık: {s.witness || "-"}</div></td><td className="p-4"><div className="flex flex-wrap gap-2"><button type="button" onClick={() => edit(s)} className="inline-flex items-center gap-1 px-3 py-2 rounded-lg bg-amber-100 hover:bg-amber-200 text-amber-900 font-black"><Pencil className="w-4 h-4" /> Düzelt</button><button type="button" onClick={() => remove(s)} className="inline-flex items-center gap-1 px-3 py-2 rounded-lg bg-red-100 hover:bg-red-200 text-red-900 font-black"><Trash2 className="w-4 h-4" /> Sil</button><button type="button" onClick={() => downloadPdf(s)} className="inline-flex items-center gap-1 px-3 py-2 rounded-lg bg-blue-100 hover:bg-blue-200 text-blue-900 font-black"><Download className="w-4 h-4" /> PDF</button></div></td></tr>)}</tbody></table></div>}</div>
  </div>;
}
