import { useEffect, useState } from "react";
import api from "@/lib/api";
import * as XLSX from "xlsx";
import { toast } from "sonner";
import { Cable, CheckCircle2, Download, FileSpreadsheet, Loader2, Plus, Trash2, Upload } from "lucide-react";

const input = "w-full h-11 bg-slate-950 border border-slate-700 rounded-lg px-3 outline-none focus:ring-2 focus:ring-violet-500";
const label = "block text-[11px] font-semibold text-slate-400 mb-1 uppercase tracking-wider";
export default function Recipes() {
  const [products,setProducts]=useState([]),[holders,setHolders]=useState([]),[machines,setMachines]=useState([]),[recipes,setRecipes]=useState([]),[name,setName]=useState(""),[workpiece,setWorkpiece]=useState(""),[note,setNote]=useState(""),[kind,setKind]=useState("product"),[ref,setRef]=useState(""),[qty,setQty]=useState("1"),[lines,setLines]=useState([]),[saving,setSaving]=useState(false),[bindFor,setBindFor]=useState(""),[machine,setMachine]=useState("");
  const load=async()=>{try{const [p,h,m,r]=await Promise.all([api.get("/products"),api.get("/toolholders"),api.get("/machines"),api.get("/recipes")]);setProducts(p.data);setHolders(h.data);setMachines(m.data);setRecipes(r.data);}catch(e){toast.error(e.response?.data?.detail||"Reçeteler yüklenemedi");}}; useEffect(()=>{load();},[]);
  const source=kind==="product"?products:holders;
  const addLine=()=>{const item=source.find(x=>x.id===ref);if(!item)return toast.error("Stok kaydı seçin");const n=Number(qty);if(!n||n<=0)return toast.error("Miktar girin");setLines([...lines,{kind,reference_id:item.id,name:item.name,code:item.code||"",quantity:n}]);setRef("");setQty("1");};
  const create=async(e)=>{e.preventDefault();if(!name||!workpiece)return toast.error("Reçete adı ve işlenecek ürün zorunlu");if(!lines.length)return toast.error("En az bir satır ekleyin");setSaving(true);try{await api.post("/recipes",{name,workpiece_name:workpiece,note,lines});toast.success("Reçete oluşturuldu; stok henüz düşmedi");setName("");setWorkpiece("");setNote("");setLines([]);await load();}catch(e){toast.error(e.response?.data?.detail||"Reçete oluşturulamadı");}finally{setSaving(false);}};
  const bind=async()=>{if(!bindFor||!machine)return toast.error("Reçete ve tezgâh seçin");if(!window.confirm("Reçetedeki tüm kalemler stoktan düşülüp tezgâha bağlanacak. Devam edilsin mi?"))return;setSaving(true);try{await api.post(`/recipes/${bindFor}/bind`,{machine_id:machine});toast.success("Reçete tezgâha bağlandı ve stoktan düşüldü");setBindFor("");setMachine("");await load();}catch(e){toast.error(e.response?.data?.detail||"Reçete bağlanamadı");}finally{setSaving(false);}};
  const exportExcel=()=>{const rows=[];recipes.forEach(r=>(r.lines||[]).forEach((l)=>rows.push({"Reçete Adı":r.name||"","İşlenecek Ürün":r.workpiece_name||"","Not":r.note||"","Durum":r.status||"draft","Tezgâh":r.machine_name||"","Satır Türü":l.kind==="toolholder"?"Takım tutucu":"Ürün / takım","Stok Kayıt ID":l.reference_id||"","Stok Kayıt Adı":l.name||"","Kod":l.code||"","Miktar":l.quantity||0})));const ws=XLSX.utils.json_to_sheet(rows);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"İşleme Reçeteleri");XLSX.writeFile(wb,`isleme-receteleri-${new Date().toISOString().slice(0,10)}.xlsx`);toast.success(`${recipes.length} reçete Excel'e aktarıldı`);};
  const template=()=>{const row={recipe_name:"Örnek Reçete",workpiece_name:"Örnek Parça",note:"Örnek açıklama",kind:"product",reference_id:"STOK_KAYIT_ID",line_name:"Örnek Ürün",code:"",quantity:1};const ws=XLSX.utils.json_to_sheet([row]);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Reçete Şablonu");XLSX.writeFile(wb,"isleme-recetesi-sablonu.xlsx");toast.success("Örnek reçete şablonu indirildi");};
  const importExcel=async(e)=>{const file=e.target.files?.[0];e.target.value="";if(!file)return;try{const data=await file.arrayBuffer(),book=XLSX.read(data,{type:"array"}),rows=XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]],{defval:""});if(!rows.length)return toast.error("Excel dosyasında kayıt yok");const groups={};rows.forEach((row)=>{const name=row["Reçete Adı"]||row.recipe_name||"İçe Aktarılan Reçete",workpiece=row["İşlenecek Ürün"]||row.workpiece_name||"",key=`${name}||${workpiece}`;(groups[key] ||= {name,workpiece_name:workpiece,note:row["Not"]||row.note||"",lines:[]}).lines.push({kind:row["Satır Türü"]==="Takım tutucu"||row.kind==="toolholder"?"toolholder":"product",reference_id:row["Stok Kayıt ID"]||row.reference_id||"",name:row["Stok Kayıt Adı"]||row.line_name||"",code:row.Kod||row.code||"",quantity:Number(row.Miktar??row.quantity)||1});});setSaving(true);let count=0;for(const r of Object.values(groups)){if(!r.name||!r.workpiece_name||!r.lines.length)continue;await api.post("/recipes",r);count++;}toast.success(`${count} reçete taslak olarak içe aktarıldı; stok düşmedi`);await load();}catch(e){toast.error(e.response?.data?.detail||"Excel içe aktarılamadı");}finally{setSaving(false);}};
  return <div className="space-y-6"><div className="flex items-end justify-between flex-wrap gap-4"><div><div className="text-xs text-violet-400 uppercase tracking-[.2em] font-semibold mb-2">İşleme Hazırlığı</div><h1 className="font-display text-4xl font-black">İşleme Reçeteleri</h1><p className="text-slate-400 mt-1">Ürün ve takım tutucuları reçeteye ekleyin; stok düşümü yalnızca reçete tezgâha bağlandığında yapılır.</p></div><div className="flex gap-2 flex-wrap"><button type="button" onClick={template} className="h-11 px-4 rounded-lg bg-slate-800 border border-slate-700 text-slate-100 font-semibold flex items-center gap-2"><FileSpreadsheet className="w-4 h-4"/> Örnek Şablon</button><button type="button" onClick={exportExcel} className="h-11 px-4 rounded-lg bg-emerald-700 hover:bg-emerald-600 text-white font-semibold flex items-center gap-2"><Download className="w-4 h-4"/> Dışa Aktar</button><label className="h-11 px-4 rounded-lg bg-blue-700 hover:bg-blue-600 text-white font-semibold flex items-center gap-2 cursor-pointer"><Upload className="w-4 h-4"/> İçe Aktar<input type="file" accept=".xlsx,.xls,.csv" onChange={importExcel} className="hidden"/></label></div></div>
    <form onSubmit={create} className="bg-slate-800/60 border border-slate-700 rounded-2xl p-6 space-y-5"><div className="flex items-center gap-2 text-violet-300 font-semibold"><Cable className="w-5 h-5"/>Yeni reçete</div><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><div><label className={label}>Reçete adı</label><input required value={name} onChange={e=>setName(e.target.value)} className={input} placeholder="Örn. Gövde-01 Kaba Tornalama"/></div><div><label className={label}>İşlenecek ürün</label><input required value={workpiece} onChange={e=>setWorkpiece(e.target.value)} className={input} placeholder="Parça adı / kodu"/></div><div><label className={label}>Not</label><input value={note} onChange={e=>setNote(e.target.value)} className={input}/></div></div><div className="grid grid-cols-1 md:grid-cols-4 gap-4 items-end"><div><label className={label}>Satır türü</label><select value={kind} onChange={e=>{setKind(e.target.value);setRef("")}} className={input}><option value="product">Stoktaki ürün / takım</option><option value="toolholder">Stoktaki takım tutucu</option></select></div><div className="md:col-span-2"><label className={label}>{kind==="product"?"Stoktaki ürün / takım":"Stoktaki takım tutucu"}</label><select value={ref} onChange={e=>setRef(e.target.value)} className={input}><option value="">Seçin</option>{source.map(x=><option key={x.id} value={x.id}>{x.code?`${x.code} — `:""}{x.name} | Stok: {x.current_stock}</option>)}</select></div><div><label className={label}>Miktar</label><div className="flex gap-2"><input type="number" min="0.01" step="0.01" value={qty} onChange={e=>setQty(e.target.value)} className={input}/><button type="button" onClick={addLine} className="h-11 px-3 rounded-lg bg-violet-600 hover:bg-violet-500"><Plus className="w-5 h-5"/></button></div></div></div>{lines.length>0&&<div className="border border-slate-700 rounded-xl overflow-hidden"><table className="w-full text-sm"><thead><tr className="text-left text-slate-500"><th className="p-3">Tür</th><th className="p-3">Stok kaydı</th><th className="p-3">Miktar</th><th/></tr></thead><tbody>{lines.map((l,i)=><tr key={i} className="border-t border-slate-800"><td className="p-3">{l.kind==="product"?"Ürün / takım":"Takım tutucu"}</td><td className="p-3">{l.code} — {l.name}</td><td className="p-3 font-bold">{l.quantity}</td><td className="p-3"><button type="button" onClick={()=>setLines(lines.filter((_,j)=>j!==i))} className="text-slate-500 hover:text-red-300"><Trash2 className="w-4 h-4"/></button></td></tr>)}</tbody></table></div>}<button disabled={saving} className="h-12 px-6 rounded-lg bg-violet-600 hover:bg-violet-500 disabled:opacity-50 font-bold flex items-center gap-2">{saving?<Loader2 className="w-5 h-5 animate-spin"/>:<Plus className="w-5 h-5"/>} Reçeteyi Kaydet</button></form>
    <div className="bg-slate-800/60 border border-amber-500/30 rounded-2xl p-6 space-y-4"><div className="font-bold text-amber-300">Reçeteyi tezgâha bağla ve stoktan düş</div><p className="text-sm text-slate-400">Reçete kaydı oluşturmak stoktan düşmez. Bu bölümde tezgâh seçip bağladığınızda reçetedeki tüm satırlar stoktan düşürülür.</p><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><div><label className={label}>Taslak reçete</label><select value={bindFor} onChange={e=>setBindFor(e.target.value)} className={input}><option value="">Seçin</option>{recipes.filter(r=>r.status!=="bound").map(r=><option key={r.id} value={r.id}>{r.name} — {r.workpiece_name}</option>)}</select></div><div><label className={label}>Bağlanacak tezgâh</label><select value={machine} onChange={e=>setMachine(e.target.value)} className={input}><option value="">Seçin</option>{machines.map(m=><option key={m.id} value={m.id}>{m.code} — {m.name}</option>)}</select></div><div className="flex items-end"><button onClick={bind} disabled={saving} className="h-11 px-5 rounded-lg bg-amber-600 hover:bg-amber-500 font-bold flex items-center gap-2"><CheckCircle2 className="w-5 h-5"/>Bağlandı ve Stoktan Düş</button></div></div></div>
    <div className="bg-slate-800/60 border border-slate-700 rounded-2xl overflow-hidden"><div className="p-5 border-b border-slate-700 font-bold">Reçete kayıtları</div><table className="w-full text-sm"><thead><tr className="text-left text-slate-500"><th className="p-4">Reçete</th><th className="p-4">İşlenecek ürün</th><th className="p-4">Kalem</th><th className="p-4">Durum</th><th className="p-4">Tezgâh</th></tr></thead><tbody>{recipes.map(r=><tr key={r.id} className="border-t border-slate-800"><td className="p-4 font-semibold">{r.name}</td><td className="p-4">{r.workpiece_name}</td><td className="p-4">{r.lines?.length||0} kalem</td><td className="p-4"><span className={r.status==="bound"?"text-emerald-300":"text-amber-300"}>{r.status==="bound"?"Tezgâha bağlı":"Taslak — stok düşmedi"}</span></td><td className="p-4">{r.machine_name||"-"}</td></tr>)}</tbody></table></div>
  </div>;
}
