import { useEffect, useMemo, useState } from "react";
import api from "@/lib/api";
import * as XLSX from "xlsx";
import { toast } from "sonner";
import { Cable, CheckCircle2, Download, FileSpreadsheet, Loader2, Plus, Search, Trash2, Upload } from "lucide-react";

const input = "w-full h-11 bg-slate-950 border border-slate-700 rounded-lg px-3 outline-none focus:ring-2 focus:ring-violet-500";
const label = "block text-[11px] font-semibold text-slate-400 mb-1 uppercase tracking-wider";
const norm = (value = "") => value.toLocaleLowerCase("tr-TR").normalize("NFD").replace(/[\u0300-\u036f]/g, "");

function SearchSelect({ labelText, value, onChange, search, setSearch, items, placeholder }) {
  const filtered = useMemo(() => {
    const q = norm(search);
    return items.filter((x) => !q || norm(`${x.code || ""} ${x.name || ""} ${x.brand || ""}`).includes(q));
  }, [items, search]);
  return <div>
    <label className={label}>{labelText}</label>
    <div className="relative mb-2"><Search className="absolute left-3 top-3 w-4 h-4 text-slate-500" /><input value={search} onChange={(e) => setSearch(e.target.value)} className={`${input} pl-9`} placeholder={placeholder} /></div>
    <select value={value} onChange={(e) => onChange(e.target.value)} className={input}>
      <option value="">Seçin</option>
      {filtered.map((x) => <option key={x.id} value={x.id}>{x.code ? `${x.code} — ` : ""}{x.name}{x.brand ? ` | Marka: ${x.brand}` : ""} | Stok: {x.current_stock ?? 0}</option>)}
    </select>
  </div>;
}

export default function Recipes() {
  const [products, setProducts] = useState([]), [holders, setHolders] = useState([]), [machines, setMachines] = useState([]), [recipes, setRecipes] = useState([]);
  const [name, setName] = useState(""), [workpiece, setWorkpiece] = useState(""), [note, setNote] = useState("");
  const [productRef, setProductRef] = useState(""), [holderRef, setHolderRef] = useState(""), [productQty, setProductQty] = useState("1"), [holderQty, setHolderQty] = useState("1");
  const [productSearch, setProductSearch] = useState(""), [holderSearch, setHolderSearch] = useState(""), [lines, setLines] = useState([]), [saving, setSaving] = useState(false), [bindFor, setBindFor] = useState(""), [machine, setMachine] = useState("");

  const load = async () => { try { const [p, h, m, r] = await Promise.all([api.get("/products"), api.get("/toolholders"), api.get("/machines"), api.get("/recipes")]); setProducts(p.data); setHolders(h.data); setMachines(m.data); setRecipes(r.data); } catch (e) { toast.error(e.response?.data?.detail || "Reçeteler yüklenemedi"); } };
  useEffect(() => { load(); }, []);

  const addPair = () => {
    const product = products.find((x) => x.id === productRef), holder = holders.find((x) => x.id === holderRef);
    if (!product || !holder) return toast.error("Ürün ve takım tutucuyu birlikte seçin");
    const pq = Number(productQty), hq = Number(holderQty);
    if (!pq || pq <= 0 || !hq || hq <= 0) return toast.error("Ürün ve tutucu miktarlarını girin");
    const pairId = `pair-${Date.now()}`;
    setLines((prev) => [...prev, { pairId, product: { kind: "product", pair_id: pairId, reference_id: product.id, name: product.name, code: product.code || "", quantity: pq, brand: product.brand || "" }, holder: { kind: "toolholder", pair_id: pairId, reference_id: holder.id, name: holder.name, code: holder.code || "", quantity: hq, brand: holder.brand || "" } }]);
    setProductRef(""); setHolderRef(""); setProductSearch(""); setHolderSearch(""); setProductQty("1"); setHolderQty("1");
  };
  const removePair = (pairId) => setLines((prev) => prev.filter((x) => x.pairId !== pairId));
  const create = async (e) => { e.preventDefault(); if (!name || !workpiece) return toast.error("Reçete adı ve işlenecek ürün zorunlu"); if (!lines.length) return toast.error("En az bir ürün-tutucu satırı ekleyin"); setSaving(true); try { await api.post("/recipes", { name, workpiece_name: workpiece, note, lines: lines.flatMap((x) => [x.product, x.holder]) }); toast.success("Reçete oluşturuldu; stok henüz düşmedi"); setName(""); setWorkpiece(""); setNote(""); setLines([]); await load(); } catch (e) { toast.error(e.response?.data?.detail || "Reçete oluşturulamadı"); } finally { setSaving(false); } };
  const bind = async () => { if (!bindFor || !machine) return toast.error("Reçete ve tezgâh seçin"); if (!window.confirm("Reçetedeki ürün ve takım tutucu kalemleri stoktan düşülüp tezgâha bağlanacak. Devam edilsin mi?")) return; setSaving(true); try { await api.post(`/recipes/${bindFor}/bind`, { machine_id: machine }); toast.success("Reçete tezgâha bağlandı; ürün ve tutucu stokları düşüldü"); setBindFor(""); setMachine(""); await load(); } catch (e) { toast.error(e.response?.data?.detail || "Reçete bağlanamadı"); } finally { setSaving(false); } };
  const exportExcel = () => { const rows = []; recipes.forEach((r) => (r.lines || []).forEach((l) => rows.push({ "Reçete Adı": r.name || "", "İşlenecek Ürün": r.workpiece_name || "", Not: r.note || "", Durum: r.status || "draft", Tezgâh: r.machine_name || "", "Satır Türü": l.kind === "toolholder" ? "Takım tutucu" : "Ürün / takım", "Stok Kayıt Adı": l.name || "", Marka: l.brand || "", Kod: l.code || "", Miktar: l.quantity || 0 }))); const ws = XLSX.utils.json_to_sheet(rows); ws["!autofilter"] = { ref: `A1:K${Math.max(1, rows.length + 1)}` }; const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, ws, "İşleme Reçeteleri"); XLSX.writeFile(wb, `isleme-receteleri-${new Date().toISOString().slice(0, 10)}.xlsx`); toast.success(`${recipes.length} reçete Excel'e aktarıldı`); };
  const template = () => { const row = { "Reçete Adı": "Örnek Reçete", "İşlenecek Ürün": "Örnek Parça", Not: "Örnek açıklama", "Ürün Kodu": "UÇ-001", "Ürün Adı": "Örnek Kesici Uç", "Ürün Miktarı": 1, "Tutucu Kodu": "TH-001", "Tutucu Adı": "Örnek Tutucu", "Tutucu Miktarı": 1 }; const ws = XLSX.utils.json_to_sheet([row]); const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, ws, "Reçete Şablonu"); XLSX.writeFile(wb, "isleme-recetesi-sablonu.xlsx"); toast.success("Örnek reçete şablonu indirildi"); };
  const importExcel = async (e) => { const file = e.target.files?.[0]; e.target.value = ""; if (!file) return; try { const data = await file.arrayBuffer(), book = XLSX.read(data, { type: "array" }), rows = XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]], { defval: "" }); if (!rows.length) return toast.error("Excel dosyasında kayıt yok"); let count = 0; for (const row of rows) { const product = products.find((x) => x.code === (row["Ürün Kodu"] || row.code)) || products.find((x) => norm(x.name) === norm(row["Ürün Adı"])); const holder = holders.find((x) => x.code === (row["Tutucu Kodu"] || row.holder_code)) || holders.find((x) => norm(x.name) === norm(row["Tutucu Adı"])); if (!product || !holder) continue; await api.post("/recipes", { name: row["Reçete Adı"] || "İçe Aktarılan Reçete", workpiece_name: row["İşlenecek Ürün"] || "", note: row.Not || "", lines: [{ kind: "product", reference_id: product.id, quantity: Number(row["Ürün Miktarı"]) || 1, pair_id: `import-${Date.now()}-${count}` }, { kind: "toolholder", reference_id: holder.id, quantity: Number(row["Tutucu Miktarı"]) || 1, pair_id: `import-${Date.now()}-${count}` }] }); count++; } toast.success(`${count} reçete taslak olarak içe aktarıldı; stok düşmedi`); await load(); } catch (e) { toast.error(e.response?.data?.detail || "Excel içe aktarılamadı"); } finally { setSaving(false); } };

  return <div className="space-y-6">
    <div className="flex items-end justify-between flex-wrap gap-4"><div><div className="text-xs text-violet-400 uppercase tracking-[.2em] font-semibold mb-2">İşleme Hazırlığı</div><h1 className="font-display text-4xl font-black">İşleme Reçeteleri</h1><p className="text-slate-400 mt-1">Ürünü ve takım tutucuyu birlikte seçin; stok düşümü yalnızca reçete tezgâha bağlandığında yapılır.</p></div><div className="flex gap-2 flex-wrap"><button type="button" onClick={template} className="h-11 px-4 rounded-lg bg-slate-800 border border-slate-700 text-slate-100 font-semibold flex items-center gap-2"><FileSpreadsheet className="w-4 h-4"/> Örnek Şablon</button><button type="button" onClick={exportExcel} className="h-11 px-4 rounded-lg bg-emerald-700 hover:bg-emerald-600 text-white font-semibold flex items-center gap-2"><Download className="w-4 h-4"/> Excel’e Aktar</button><label className="h-11 px-4 rounded-lg bg-blue-700 hover:bg-blue-600 text-white font-semibold flex items-center gap-2 cursor-pointer"><Upload className="w-4 h-4"/> İçe Aktar<input type="file" accept=".xlsx,.xls,.csv" onChange={importExcel} className="hidden"/></label></div></div>
    <form onSubmit={create} className="bg-slate-800/60 border border-slate-700 rounded-2xl p-6 space-y-5"><div className="flex items-center gap-2 text-violet-300 font-semibold"><Cable className="w-5 h-5"/>Yeni reçete</div><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><div><label className={label}>Reçete adı</label><input required value={name} onChange={(e) => setName(e.target.value)} className={input} placeholder="Örn. Gövde-01 Kaba Tornalama"/></div><div><label className={label}>İşlenecek ürün</label><input required value={workpiece} onChange={(e) => setWorkpiece(e.target.value)} className={input} placeholder="Parça adı / kodu"/></div><div><label className={label}>Not</label><input value={note} onChange={(e) => setNote(e.target.value)} className={input}/></div></div>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5"><div className="rounded-xl border border-violet-500/40 bg-violet-950/20 p-4"><div className="text-violet-200 font-black mb-3">1. Stoktaki ürün / takım</div><SearchSelect labelText="Ürün ara ve seç" value={productRef} onChange={setProductRef} search={productSearch} setSearch={setProductSearch} items={products} placeholder="Kod, ürün adı veya marka yazın"/><label className={`${label} mt-3`}>Ürün miktarı</label><input type="number" min="0.01" step="0.01" value={productQty} onChange={(e) => setProductQty(e.target.value)} className={input}/></div><div className="rounded-xl border border-amber-500/40 bg-amber-950/20 p-4"><div className="text-amber-200 font-black mb-3">2. Takım tutucu</div><SearchSelect labelText="Tutucu ara ve seç" value={holderRef} onChange={setHolderRef} search={holderSearch} setSearch={setHolderSearch} items={holders} placeholder="Kod, tutucu adı veya marka yazın"/><label className={`${label} mt-3`}>Tutucu miktarı</label><input type="number" min="0.01" step="0.01" value={holderQty} onChange={(e) => setHolderQty(e.target.value)} className={input}/></div></div>
      <button type="button" onClick={addPair} className="h-11 px-4 rounded-lg bg-violet-600 hover:bg-violet-500 font-bold flex items-center gap-2"><Plus className="w-5 h-5"/> Ürün + Tutucuyu Reçeteye Ekle</button>
      {lines.length > 0 && <div className="border border-violet-500/40 rounded-xl overflow-hidden"><div className="px-4 py-3 bg-violet-950/30 text-violet-200 font-bold">Birleşik reçete kalemleri ({lines.length}) — Her satırda ürün ve tutucu birlikte düşer</div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-slate-400"><th className="p-3">#</th><th className="p-3">Stoktaki ürün</th><th className="p-3">Ürün miktarı</th><th className="p-3">Takım tutucu</th><th className="p-3">Tutucu miktarı</th><th/></tr></thead><tbody>{lines.map((l, i) => <tr key={l.pairId} className="border-t border-slate-800"><td className="p-3">{i + 1}</td><td className="p-3 font-semibold">{l.product.code ? `${l.product.code} — ` : ""}{l.product.name}<div className="text-xs text-slate-500">{l.product.brand || "Marka yok"}</div></td><td className="p-3 font-bold">{l.product.quantity}</td><td className="p-3 font-semibold">{l.holder.code ? `${l.holder.code} — ` : ""}{l.holder.name}<div className="text-xs text-slate-500">{l.holder.brand || "Marka yok"}</div></td><td className="p-3 font-bold">{l.holder.quantity}</td><td className="p-3"><button type="button" onClick={() => removePair(l.pairId)} className="text-slate-500 hover:text-red-300" title="Kalemi sil"><Trash2 className="w-4 h-4"/></button></td></tr>)}</tbody></table></div></div>}
      <button disabled={saving} className="h-12 px-6 rounded-lg bg-violet-600 hover:bg-violet-500 disabled:opacity-50 font-bold flex items-center gap-2">{saving ? <Loader2 className="w-5 h-5 animate-spin"/> : <Plus className="w-5 h-5"/>} Reçeteyi Kaydet</button>
    </form>
    <div className="bg-slate-800/60 border border-amber-500/30 rounded-2xl p-6 space-y-4"><div className="font-bold text-amber-300">Reçeteyi tezgâha bağla ve stoktan düş</div><p className="text-sm text-slate-400">Taslak kaydetmek stoktan düşmez. Tezgâh seçip bağladığınızda reçetedeki ürün ve tutucu kalemlerinin tamamı stoktan düşürülür.</p><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><div><label className={label}>Taslak reçete</label><select value={bindFor} onChange={(e) => setBindFor(e.target.value)} className={input}><option value="">Seçin</option>{recipes.filter((r) => r.status !== "bound").map((r) => <option key={r.id} value={r.id}>{r.name} — {r.workpiece_name}</option>)}</select></div><div><label className={label}>Bağlanacak tezgâh</label><select value={machine} onChange={(e) => setMachine(e.target.value)} className={input}><option value="">Seçin</option>{machines.map((m) => <option key={m.id} value={m.id}>{m.code} — {m.name}</option>)}</select></div><div className="flex items-end"><button type="button" onClick={bind} disabled={saving} className="h-11 px-5 rounded-lg bg-amber-600 hover:bg-amber-500 font-bold flex items-center gap-2"><CheckCircle2 className="w-5 h-5"/>Bağlandı ve Stoktan Düş</button></div></div></div>
    <div className="bg-slate-800/60 border border-slate-700 rounded-2xl overflow-hidden"><div className="p-5 border-b border-slate-700 font-bold">Reçete kayıtları</div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-slate-400"><th className="p-4">Reçete</th><th className="p-4">İşlenecek ürün</th><th className="p-4">Kalem</th><th className="p-4">Durum</th><th className="p-4">Tezgâh</th></tr></thead><tbody>{recipes.map((r) => <tr key={r.id} className="border-t border-slate-800"><td className="p-4 font-semibold">{r.name}</td><td className="p-4">{r.workpiece_name}</td><td className="p-4">{r.lines?.filter((l) => l.kind === "product").length || 0} ürün + {r.lines?.filter((l) => l.kind === "toolholder").length || 0} tutucu</td><td className="p-4"><span className={r.status === "bound" ? "text-emerald-300" : "text-amber-300"}>{r.status === "bound" ? "Tezgâha bağlı" : "Taslak — stok düşmedi"}</span></td><td className="p-4">{r.machine_name || "-"}</td></tr>)}</tbody></table></div></div>
  </div>;
}
