import { useEffect, useMemo, useState } from "react";
import api from "@/lib/api";
import { toast } from "sonner";
import { BarChart3, Loader2, Plus, Search, Trash2, Trophy } from "lucide-react";

const today = () => new Date().toISOString().slice(0, 10);
const input = "w-full h-11 bg-slate-950 border border-slate-700 rounded-lg px-3 outline-none focus:ring-2 focus:ring-blue-500";
const label = "block text-[11px] font-semibold text-slate-400 mb-1 uppercase tracking-wider";
const blank = { comparison_name: "", trial_date: today(), part_name: "", material: "", hardness: "", machine_id: "", operation_type: "Tornalama", product_id: "", product_brand: "", product_code: "", insert_grade: "", tool_diameter: "", quantity_used: "", price: "", spindle_speed: "", cutting_speed: "", feed_rate: "", depth_of_cut: "", drill_diameter: "", feed_per_tooth: "", runtime_minutes: "", parts_machined: "", wear_result: "", result: "", technical_comment: "", coolant: "" };

export default function ToolTrials() {
  const [products, setProducts] = useState([]), [machines, setMachines] = useState([]), [trials, setTrials] = useState([]), [form, setForm] = useState(blank), [query, setQuery] = useState(""), [saving, setSaving] = useState(false);
  const load = async () => { try { const [p, m, t] = await Promise.all([api.get("/products"), api.get("/machines"), api.get("/tool-trials")]); setProducts(p.data); setMachines(m.data); setTrials(t.data); } catch (e) { toast.error(e.response?.data?.detail || "Denemeler yüklenemedi"); } };
  useEffect(() => { load(); }, []);
  const set = (k, v) => setForm((f) => ({ ...f, [k]: v }));
  const selected = products.find((p) => p.id === form.product_id);
  const filtered = useMemo(() => { const q = query.toLowerCase(); return trials.filter((t) => !q || `${t.comparison_name} ${t.part_name} ${t.product_brand} ${t.product_code} ${t.insert_grade}`.toLowerCase().includes(q)); }, [trials, query]);
  const submit = async (e) => { e.preventDefault(); setSaving(true); try { await api.post("/tool-trials", { ...form, product_brand: selected?.brand || form.product_brand, product_code: selected?.code || form.product_code, quantity_used: Number(form.quantity_used) || 0, price: Number(form.price) || 0, runtime_minutes: Number(form.runtime_minutes) || 0, parts_machined: Number(form.parts_machined) || 0, machine_id: form.machine_id || null, product_id: form.product_id || null }); toast.success("Deneme raporu kaydedildi"); setForm(blank); await load(); } catch (e) { toast.error(e.response?.data?.detail || "Deneme kaydedilemedi"); } finally { setSaving(false); } };
  const remove = async (id) => { if (!window.confirm("Bu deneme silinsin mi?")) return; try { await api.delete(`/tool-trials/${id}`); load(); } catch (e) { toast.error(e.response?.data?.detail || "Silinemedi"); } };
  const grouped = Object.values(filtered.reduce((a, t) => { const k = t.comparison_name || "Grupsuz"; (a[k] ||= []).push(t); return a; }, {}));
  return <div className="space-y-6"><div><div className="text-xs text-blue-400 uppercase tracking-[.2em] font-semibold mb-2">Kesici Takım Performansı</div><h1 className="font-display text-4xl font-black">Deneme ve Marka Karşılaştırma</h1><p className="text-slate-400 mt-1">Matkap, freze ve kesici elmas uç denemelerini aynı iş ve parametre grubu içinde karşılaştırın.</p></div>
    <form onSubmit={submit} className="bg-slate-800/60 border border-slate-700 rounded-2xl p-6 space-y-5"><div className="flex items-center gap-2 text-blue-300 font-semibold"><BarChart3 className="w-5 h-5" />Deneme raporu kartı</div>
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">{[["comparison_name","Karşılaştırma grubu","Örn. DNMG 150608 - Döküm"],["trial_date","Tarih",""],["part_name","İşlenen ürün / parça",""],["material","Malzeme ve sertlik","Örn. GG25 / 180 HB"]].map(([k,l,p])=><div key={k}><label className={label}>{l}</label><input required={k !== "comparison_name"} type={k === "trial_date" ? "date" : "text"} value={form[k]} placeholder={p} onChange={e=>set(k,e.target.value)} className={input}/></div>)}</div>
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4"><div><label className={label}>Tezgâh</label><select value={form.machine_id} onChange={e=>set("machine_id",e.target.value)} className={input}><option value="">Seçin</option>{machines.map(m=><option key={m.id} value={m.id}>{m.code} — {m.name}</option>)}</select></div><div><label className={label}>İş türü</label><select value={form.operation_type} onChange={e=>set("operation_type",e.target.value)} className={input}>{["Tornalama","Frezeleme","Delme","Diş açma","Diğer"].map(x=><option key={x}>{x}</option>)}</select></div><div><label className={label}>Stoktaki ürün / uç</label><select value={form.product_id} onChange={e=>set("product_id",e.target.value)} className={input}><option value="">Elle yazacağım</option>{products.map(p=><option key={p.id} value={p.id}>{p.code} — {p.name}</option>)}</select></div><div><label className={label}>Marka</label><input value={selected?.brand || form.product_brand} onChange={e=>set("product_brand",e.target.value)} className={input}/></div></div>
      <div className="grid grid-cols-2 md:grid-cols-6 gap-4">{[["product_code","Ürün / uç kodu"],["insert_grade","Uç kodu ve kalite"],["tool_diameter","Takım çapı"],["spindle_speed","Devir N"],["cutting_speed","Kesme hızı Vc"],["feed_rate","İlerleme F"],["depth_of_cut","Paso ap"],["drill_diameter","Matkap çapı"],["feed_per_tooth","Diş başı fz"],["coolant","Soğutma"],["quantity_used","Kullanılan miktar"],["price","Birim fiyat"]].map(([k,l])=><div key={k}><label className={label}>{l}</label><input value={form[k]} onChange={e=>set(k,e.target.value)} className={input}/></div>)}</div>
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">{[["runtime_minutes","Çalışma süresi (dk)"],["parts_machined","İşlenen parça adedi"],["wear_result","Aşınma / takım ömrü"],["result","Test sonucu"],["technical_comment","Teknik yorum"]].map(([k,l])=><div key={k} className={k === "technical_comment" ? "md:col-span-2" : ""}><label className={label}>{l}</label><input value={form[k]} onChange={e=>set(k,e.target.value)} className={input}/></div>)}</div>
      <button disabled={saving} className="h-12 px-6 rounded-lg bg-blue-600 hover:bg-blue-500 disabled:opacity-50 font-bold flex items-center gap-2">{saving ? <Loader2 className="w-5 h-5 animate-spin"/> : <Plus className="w-5 h-5"/>} Deneme Kaydet</button>
    </form>
    <div className="relative"><Search className="absolute left-3 top-3 w-4 h-4 text-slate-500"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Marka, uç kodu, parça veya karşılaştırma ara..." className={`${input} pl-10`}/></div>
    <div className="bg-slate-800/60 border border-slate-700 rounded-2xl overflow-hidden"><div className="p-5 border-b border-slate-700 flex gap-2 items-center"><Trophy className="w-5 h-5 text-amber-300"/><h2 className="font-bold">Karşılaştırmalı sonuçlar</h2></div>{grouped.map((rows,i)=><div key={i} className="p-5 border-b border-slate-800"><h3 className="font-semibold text-blue-300 mb-3">{rows[0].comparison_name || "Grupsuz"}</h3><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-slate-500"><th className="p-2">Marka / Kod</th><th className="p-2">İş türü</th><th className="p-2">Vc / F / ap</th><th className="p-2">Parça</th><th className="p-2">Süre</th><th className="p-2">Sonuç</th><th/></tr></thead><tbody>{rows.map(t=><tr key={t.id} className="border-t border-slate-800"><td className="p-2">{t.product_brand || "-"}<div className="text-slate-500">{t.product_code || t.insert_grade}</div></td><td className="p-2">{t.operation_type}</td><td className="p-2">{t.cutting_speed || "-"} / {t.feed_rate || "-"} / {t.depth_of_cut || "-"}</td><td className="p-2 font-bold text-emerald-300">{t.parts_machined || 0}</td><td className="p-2">{t.runtime_minutes || 0} dk</td><td className="p-2">{t.result || t.wear_result || "-"}</td><td className="p-2"><button onClick={()=>remove(t.id)} className="text-slate-500 hover:text-red-300"><Trash2 className="w-4 h-4"/></button></td></tr>)}</tbody></table></div></div>)}</div>
  </div>;
}
